config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'login/index'
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # root "home#index"
  root to: "home#index"
  get "/register", to:"register#index"
  get "/login", to:"login#index"
  get "users/profile", to:"profile#index"
  get "/dashboard", to:"dashboard#index"

  # resources :boards, only: [:new, :edit, :create, :update, :destroy, :show]

  resources :boards do
    resources :lists, except: :show
    resources :board_users, only: [:new, :create]
  end

  resources :items do
    resources :item_members, only: [:new, :create]
  end

  resources :lists do
    resources :items
  end

  resources :items do
    resources :child_issues, only: [:new, :create, :edit, :update, :destroy]
  end

  namespace :api do
    resources :boards do
      resources :lists, only: [:index, :update], controller: "lists"
      resources :list_positions, only: [:index, :update], controller: "list_positions"
    end
    put "item_positions", to:"item_positions#update"

    resources :items, only: [:show, :update] do
      resources :child_issues, only: [:new, :index, :edit], controller: "child_issues"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user

  validates :name, presence: true

  has_many :lists, dependent: :destroy

  has_many :board_users, dependent: :destroy

  has_many :members, through: :board_users, source: :user

  after_create :assign_user_as_member

  def assign_user_as_member
    members << user
  end

  def self.assigned_boards(user)
    joins(:members).where("users.id = ?", user.id)
  end
end

app/models/board_user.rb
class BoardUser < ApplicationRecord
  belongs_to :board
  belongs_to :user
end

app/models/child_issue.rb
class ChildIssue < ApplicationRecord
  belongs_to :item

  validates :title, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list

  validates :title, presence: true

  has_many :item_members, dependent: :destroy

  has_many :child_issues, dependent: :destroy

  accepts_nested_attributes_for :child_issues

  has_many :members, through: :item_members, source: :user

  has_one_attached :image

  def image_url
    Rails.application.routes.url_helpers.rails_blob_path(image) if image.attached?
  end

  # has_one_attached :image do |attachable|
  #   attachable.service = :cloudinary
  # end
end

app/models/item_member.rb
class ItemMember < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board

  has_many :items, dependent: :destroy

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards, dependent: :destroy
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params.merge(user: current_user))

    if @board.save
      create_default_lists
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    authorize board
  end

  def update
    authorize board
    if board.update(board_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    authorize board
    @lists = board.lists
  end

  def destroy
    authorize board
    board.destroy
    redirect_to root_path
  end

  private
  def board_params
    params.require(:board).permit(:name)
  end

  def board
    @board ||= Board.find(params[:id])
  end

  def create_default_lists
    default_lists = ['To Do', 'In Progress', 'In Review', 'Done']

    default_lists.each_with_index do |list_title, index|
      @board.lists.create(title: list_title, position: index)
    end
  end
end

app/controllers/child_issues_controller.rb
class ChildIssuesController < ApplicationController
  before_action :authenticate_user!

  # protect_from_forgery with: :null_session, only: :destroy

  def new
    @child_issue = item.child_issues.new
  end

  def create
    @child_issue = item.child_issues.new(child_issue_params)

    if @child_issue.save
      redirect_to board_path(item.list.board)
    else
      render :new
    end
  end

  def edit
    @child_issue = item.child_issues.find(params[:id])
  end

  def update
    @child_issue = item.child_issues.find(params[:id])

    if @child_issue.update(child_issue_params)
      redirect_to board_path(item.list.board)
    else
      render :edit
    end
  end

  def destroy
    @child_issue = item.child_issues.find(params[:id])
    @child_issue.destroy
    redirect_to board_path(item.list.board)
  end

  def index
    @child_issue = item.child_issues
  end

  private

  def item
    @item ||= Item.find(params[:item_id])
  end

  def child_issue_params
    params.require(:child_issue).permit(:title, :description)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
    # @boards = Board.all
    @boards = current_user.boards

    @assigned_boards = Board.assigned_boards(current_user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to dashboard_path if user_signed_in?
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!

  protect_from_forgery with: :null_session, only: :destroy

  # protect_from_forgery unless: -> { request.format.json? }

  def new
    @item = list.items.new
  end

  def edit
    @item = list.items.find(params[:id])
  end

  def create
    @item = list.items.new(item_params)

    if @item.save
      redirect_to board_path(list.board)
    else
      render :new
    end
  end

  def update
    @item = list.items.find(params[:id])

    if @item.update(item_params)
      redirect_to board_path(list.board)
    else
      render :edit
    end
  end

  def destroy
    @item = list.items.find(params[:id])

    @item.destroy

    redirect_to board_path(list.board)
  end

  private
  def list
    @list ||= List.find(params[:list_id])
  end


  def item_params
    params.require(:item).permit(:title, :description, :image, :image_url)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!

  protect_from_forgery with: :null_session, only: :destroy

  # protect_from_forgery unless: -> { request.format.json? }

  def new
    @list = board.lists.new
  end

  def edit
    @list = board.lists.find(params[:id])
  end

  def create
    @list = board.lists.new(list_params)

    @list.position = board.lists.maximum(:position).to_i + 1

    if @list.save
      redirect_to board_path(board)
    else
      render :new
    end
  end

  def update
    @list = board.lists.find(params[:id])

    if @list.update(list_params)
      redirect_to board_path(board)
    else
      render :edit
    end
  end

  def destroy
    @list = board.lists.find(params[:id])

    @list.destroy

    respond_to do |format|
      format.json do
        render json: {}, status: 200
      end
    end
  end

  private
  def board
    @board ||= Board.find(params[:board_id])
  end

  def list_params
    params.require(:list).permit(:title)
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
  end
end

app/controllers/register_controller.rb
class RegisterController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/child_issues_helper.rb
module ChildIssuesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/views/child_issues/_form.html.erb
<div class="mx-auto max--w-7xl px-4 sm:px-6 lg:px-8 py-12">
    <div class="mx-auto max-w-3xl">
        <%= form_with model: [item, child_issue], local: true, class:"space-y-8 divide-gray-200" do |f| %>
            <div class="space-y-8 divide-y divide-gray-200">
                <div>
                    <div>
                        <% if child_issue.new_record? %>
                            <h3 class="text-lg font-medium leading-6 text-gray-900">New Child Issue</h3>
                            <p class="mt-1 text-sm text-gray-500">This form creates a new child issue.</p>
                        <% else %>
                            <h3 class="text-lg font-medium leading-6 text-gray-900">Edit Child Issue</h3>
                            <p class="mt-1 text-sm text-gray-500">This form edits a child issue.</p>
                        <% end %>
                    </div>
                    <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
                        <div class="sm: col-span-6">
                            <%= f.label :title, class: "block text-sm font-medium text-gray-700" %>
                            <div class="mt-1">
                                <%= f.text_field :title, class: "block w-full rounded-md border-gray-300 shadow-focus:border-indigo-500" %>
                            </div>
                        </div>
                    </div>

                    <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
                        <div class="sm: col-span-6">
                            <%= f.label :description, class: "block text-sm font-medium text-gray-700" %>
                            <div class="mt-1">
                                <%= f.text_area :description, class: "block w-full p-3 h-40 rounded-md border-gray-300 shadow-focus:border-indigo-500" %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="pt-5">
                <div class="flex justify-end">
                    <% if @child_issue.new_record? %>
                        <%= link_to "Cancel", root_path, class: "rounded-md border border-gray-300 bg-white py-2 px-4 text-sm font-medium text-gray-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
                        <%= f.submit "Add Child Issue", class:"ml-3 inline-flex justify-center rounded-md border border-transparent text-white bg-[#0A3D62] py-2 px-4 cursor-pointer shadow-sm hover:bg-[#092A41] focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"%>
                    <% else %>
                        <%= link_to "Cancel", root_path, class: "rounded-md border border-gray-300 bg-white py-2 px-4 text-sm font-medium text-gray-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
                        <%= f.submit "Update Child Issue", class:"ml-3 inline-flex justify-center rounded-md border border-transparent text-white bg-[#0A3D62] py-2 px-4 cursor-pointer shadow-sm hover:bg-[#092A41] focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"%>
                        <div><%= link_to "Delete", item_child_issue_path(item, child_issue), data: {"turbo-method": :delete }, onclick:"alert('Are you sure?')", class: "ml-3 inline-flex justify-center rounded-md border border-transparent text-white bg-red-500 py-2 px-4 cursor-pointer" %></div>
                    <% end %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/child_issues/edit.html.erb
<%= render "form", item: @item, child_issue: @child_issue %>

app/views/child_issues/new.html.erb
<div class="mx-auto max--w-7xl px-4 sm:px-6 lg:px-8 py-12">
    <div class="mx-auto max-w-3xl">
        <%= form_with model: [@item, @child_issue], local: true, class:"space-y-8 divide-gray-200" do |f| %>
            <div class="space-y-8 divide-y divide-gray-200">
                <div>
                    <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
                        <div class="sm: col-span-6">
                            <%= f.label :title, class: "block text-sm font-medium text-gray-700" %>
                            <div class="mt-1">
                                <%= f.text_field :title, class: "block w-full rounded-md border-gray-300 shadow-focus:border-indigo-500" %>
                            </div>
                        </div>
                    </div>

                    <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
                        <div class="sm: col-span-6">
                            <%= f.label :description, class: "block text-sm font-medium text-gray-700" %>
                            <div class="mt-1">
                                <%= f.text_area :description, class: "block w-full p-3 h-40 rounded-md border-gray-300 shadow-focus:border-indigo-500" %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="pt-5">
                <div class="flex justify-end">
                    <%= link_to "Cancel", root_path, class: "rounded-md border border-gray-300 bg-white py-2 px-4 text-sm font-medium text-gray-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
                    <%= f.submit "Create Child Issue", class:"ml-3 inline-flex justify-center rounded-md border border-transparent text-white bg-[#0A3D62] py-2 px-4 cursor-pointer shadow-sm hover:bg-[#092A41] focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"%>
                </div>
            </div>
        <% end %>
    </div>
</div>