config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'login/index'
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # root "home#index"
  root to: "home#index"
  get "/register", to:"register#index"
  get "/login", to:"login#index"
  get "users/profile", to:"profile#index"
  get "/dashboard", to:"dashboard#index"

  # resources :boards, only: [:new, :edit, :create, :update, :destroy, :show]

  resources :boards do
    resources :lists, except: :show
    resources :board_users, only: [:new, :create]
  end

  resources :items do
    resources :item_members, only: [:new, :create]
  end

  resources :lists do
    resources :items
  end

  resources :items do
    resources :child_issues, only: [:new, :create, :edit, :update, :destroy]
  end

  namespace :api do
    resources :boards do
      resources :lists, only: [:index, :update], controller: "lists"
      resources :list_positions, only: [:index, :update], controller: "list_positions"
    end
    put "item_positions", to:"item_positions#update"

    resources :items, only: [:show, :update] do
      resources :child_issues, only: [:new, :index, :edit], controller: "child_issues"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user

  validates :name, presence: true

  has_many :lists, dependent: :destroy

  has_many :board_users, dependent: :destroy

  has_many :members, through: :board_users, source: :user

  after_create :assign_user_as_member

  def assign_user_as_member
    members << user
  end

  def self.assigned_boards(user)
    joins(:members).where("users.id = ?", user.id)
  end
end

app/models/board_user.rb
class BoardUser < ApplicationRecord
  belongs_to :board
  belongs_to :user
end

app/models/child_issue.rb
class ChildIssue < ApplicationRecord
  belongs_to :item

  validates :title, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list

  validates :title, presence: true

  has_many :item_members, dependent: :destroy

  has_many :child_issues, dependent: :destroy

  accepts_nested_attributes_for :child_issues

  has_many :members, through: :item_members, source: :user

  has_one_attached :image

  def image_url
    Rails.application.routes.url_helpers.rails_blob_path(image) if image.attached?
  end

  # has_one_attached :image do |attachable|
  #   attachable.service = :cloudinary
  # end
end

app/models/item_member.rb
class ItemMember < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board

  has_many :items, dependent: :destroy

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards, dependent: :destroy
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params.merge(user: current_user))

    if @board.save
      create_default_lists
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    authorize board
  end

  def update
    authorize board
    if board.update(board_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    authorize board
    @lists = board.lists
  end

  def destroy
    authorize board
    board.destroy
    redirect_to root_path
  end

  private
  def board_params
    params.require(:board).permit(:name)
  end

  def board
    @board ||= Board.find(params[:id])
  end

  def create_default_lists
    default_lists = ['To Do', 'In Progress', 'In Review', 'Done']

    default_lists.each_with_index do |list_title, index|
      @board.lists.create(title: list_title, position: index)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to dashboard_path if user_signed_in?
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!

  protect_from_forgery with: :null_session, only: :destroy

  # protect_from_forgery unless: -> { request.format.json? }

  def new
    @item = list.items.new
  end

  def edit
    @item = list.items.find(params[:id])
  end

  def create
    @item = list.items.new(item_params)

    if @item.save
      redirect_to board_path(list.board)
    else
      render :new
    end
  end

  def update
    @item = list.items.find(params[:id])

    if @item.update(item_params)
      redirect_to board_path(list.board)
    else
      render :edit
    end
  end

  def destroy
    @item = list.items.find(params[:id])

    @item.destroy

    redirect_to board_path(list.board)
  end

  private
  def list
    @list ||= List.find(params[:list_id])
  end


  def item_params
    params.require(:item).permit(:title, :description, :image, :image_url)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!

  protect_from_forgery with: :null_session, only: :destroy

  # protect_from_forgery unless: -> { request.format.json? }

  def new
    @list = board.lists.new
  end

  def edit
    @list = board.lists.find(params[:id])
  end

  def create
    @list = board.lists.new(list_params)

    @list.position = board.lists.maximum(:position).to_i + 1

    if @list.save
      redirect_to board_path(board)
    else
      render :new
    end
  end

  def update
    @list = board.lists.find(params[:id])

    if @list.update(list_params)
      redirect_to board_path(board)
    else
      render :edit
    end
  end

  def destroy
    @list = board.lists.find(params[:id])

    @list.destroy

    respond_to do |format|
      format.json do
        render json: {}, status: 200
      end
    end
  end

  private
  def board
    @board ||= Board.find(params[:board_id])
  end

  def list_params
    params.require(:list).permit(:title)
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/child_issues_helper.rb
module ChildIssuesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/views/layouts/_header.html.erb
<nav class="container px-10 py-5 mx-auto w-full">
  <div class="flex justify-between items-center">
    <% if user_signed_in? %>
        <div class="flex gap-10 items-center text-[#0A3D62]">
            <h1 class="text-4xl text-[#0A3D62]"><%= link_to "Do.it", "/" %></h1>
            <%
=begin%>
 <%= link_to "Profile", edit_user_registration_path %> 
<%
=end%>
            <%= link_to "Profile", '/users/profile' %>
            <%= link_to "Dashboard", root_path %>
            <%= button_to "Logout", destroy_user_session_path, method: :delete %>
        </div>
        <% if controller_name == "boards" && action_name == "show" %>
        <div>
            <%= link_to "+ New List", new_board_list_path(@board), class: "px-4 py-2 bg-[#0A3D62] text-[#fff] rounded-md" %>
        </div>
        <% else %>
            <div>
            <%= link_to "+ New Board", new_board_path, class: "px-4 py-2 bg-[#0A3D62] text-[#fff] rounded-md" %>
            </div>  
        <% end %>
    <% else %>
        <h1 class="text-4xl text-[#0A3D62]"><%= link_to "Do.it", "/" %></h1>
        <div class="flex gap-5 items-center text-[#0A3D62]">
            <%= link_to "Register", new_user_registration_path %>
            <%= link_to "Login", new_user_session_path %>
        </div>
    <% end %>
  </div>
</nav>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoIt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://cdn.tailwindcss.com"></script> 
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <%= render "layouts/header" %>
      <div class="flex items-center justify-center">
        <%
=begin%>
 <p class="notice"><%= notice %></p> 
<%
=end%>
        <p class="alert text-red-500"><%= alert %></p>
      </div>
      <%= yield %>
  </body>
</html>

app/views/shared/_delete.html.erb
<div
data-controller="modal"
id="modal-wrapper"
class="hidden relative z-10"
aria-labelledby="modal-title"
role="dialog"
aria-modal="true">
    <div class="hidden" id="show-modal-div" data-action="click->modal#showModal"></div>
    <!--
    Background .backdrop, show/hide based on modal state.

    Entering: "ease-out duration-300"
    From: "opacity-0"
    To: "opacity-100"
    Leaving: "ease-in duration-200"
    .From: "opacity-100"
    To: "opacity-0"
    -->
    <div
        id="modal-backdrop"
        class="hidden fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity"
        data-transition-enter="ease-out duration-300"
        data-transition-enter-start="opacity-0"
        data-transition-enter-end="opacity-100"
        data-transition-leave="ease-in duration-200"
        data-transition-leave-start="opacity-100"
        data-transition-leave-end="opacity-0"
    ></div>

    <div class="fixed z-10 inset-0 overflow-y-auto">
        <div class="flex items-end sm:items-center justify-center min-h-full p-4 text-center sm:p-0" >
            <div
                id="modal-panel"
                class="hiddlen relative bg-white w-1/3 rounded-lg px-5 pt-5 pb-4 text-left overflow-hidden shadow-xl transform transition-all"
                data-transition-enter="ease-out duration-300"
                data-tansition-enter-start="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
                data-tansition-enter-end="opacity-100 translate-y-0 sm:scale-100"
                data-transition-leave="ease-in duration-200"
                data-transition-leave-start="opacity-100 translate-y-0 sm:scale-100"
                data-transition-leave-end="opacity-0 translate-y-4 sm:translate-y-0"
            >
                <div class="flex-none w-fit cursor-pointer justify-end ml-auto" data-modal-target="closeButton" id="closeButton">x</div>

                <div class="flex flex-col gap-2">
                    <p class="font-bold">Do you want to delete?</p>

                    <div class="flex gap-5">
                        <div><%= link_to "Edit", "", class:"link text-blue-700" , id:"item-edit-link" %></div>
                        <div><%= link_to "Delete", "", class:"link text-red-700" , id:"item-delete-link", data: {"turbo-method": :delete }, onclick:"alert('Are you sure?')" %></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


app/views/shared/_modal.html.erb
<div
data-controller="modal"
id="modal-wrapper"
class="hidden relative z-10"
aria-labelledby="modal-title"
role="dialog"
aria-modal="true">
    <div class="hidden" id="show-modal-div" data-action="click->modal#showModal"></div>
    <!--
    Background .backdrop, show/hide based on modal state.

    Entering: "ease-out duration-300"
    From: "opacity-0"
    To: "opacity-100"
    Leaving: "ease-in duration-200"
    .From: "opacity-100"
    To: "opacity-0"
    -->
    <div
        id="modal-backdrop"
        class="hidden fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity"
        data-transition-enter="ease-out duration-300"
        data-transition-enter-start="opacity-0"
        data-transition-enter-end="opacity-100"
        data-transition-leave="ease-in duration-200"
        data-transition-leave-start="opacity-100"
        data-transition-leave-end="opacity-0"
    ></div>

    <div class="fixed z-10 inset-0 overflow-y-auto">
        <div class="flex items-end sm:items-center justify-center min-h-full p-4 text-center sm:p-0" >
            <div
                id="modal-panel"
                class="hiddlen relative bg-white w-1/2 rounded-lg px-5 pt-5 pb-4 text-left overflow-hidden shadow-xl transform transition-all"
                data-transition-enter="ease-out duration-300"
                data-tansition-enter-start="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
                data-tansition-enter-end="opacity-100 translate-y-0 sm:scale-100"
                data-transition-leave="ease-in duration-200"
                data-transition-leave-start="opacity-100 translate-y-0 sm:scale-100"
                data-transition-leave-end="opacity-0 translate-y-4 sm:translate-y-0"
            >
                <div class="flex-none w-fit cursor-pointer justify-end ml-auto" data-modal-target="closeButton" id="closeButton">x</div>

                <div class="flex flex-col gap-2">
                    <p class="font-bold">Title:</p>
                    <p id="item-title"></p>

                    <p class="font-bold">Description:</p>
                    <p id="item-description"></p>

                    <div class="flex flex-col gap-2 " id="item-child-issues">
                        <p class="font-bold">Child Isssues:</p>
                        <ul class="h-32 overflow-y-auto" id="item-child-issues-list">
                        </ul>
                    </div>

                    <p class="font-bold">Image:</p>
                    <img src="" id="item-image" class="object-cover h-52 w-1/2 m-auto"></img>

                    <div class="flex gap-5">
                        <div><%= link_to "Edit", "", class:"link text-blue-700" , id:"item-edit-link" %></div>
                        <div><%= link_to "Delete", "", class:"link text-red-700" , id:"item-delete-link", data: {"turbo-method": :delete }, onclick:"alert('Are you sure?')" %></div>
                    </div>

                    <div class="flex gap-5">
                        <div><%= link_to "Add Child Issues","" , class:"text-blue-700" , id:"add-child-issue-link" %></div>
                    </div>

                    <div class="flex gap-5">
                        <div><%= link_to "Assign Members To Item","" , class:"text-blue-700" , id:"item-assign-member-link" %></div>
                    </div>

                    <div class="text-lg tracking-wide" id="item-members-section">
                        <p class="font-bold">Members Assigned</p>
                        <ul id="item-members-list">
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
